app:
  replicas: 1 # increase for more fault tolerance
  resources: # increase for more than 10 concurrent annotators
    requests:
      memory: 1024Mi
      cpu: 1000m
    limits:
      memory: 6144Mi
      cpu: 4000m
